// utils/addressMappings.ts

const capitalize = (str: string): string => {
    if (!str) return '';
    return str.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
};

/**
 * A map for normalizing common address typos and formatting variations.
 * This is applied first to clean the input string before parsing.
 */
export const CITY_NORMALIZATION_MAP: Record<string, string> = {
  'калининрад': 'калининград',
  'калининграл': 'калининград',
  'калиннградская': 'калининград',
  'г красноадр': 'краснодар', // FIX for typo
  'снкт-петербург': 'санкт-петербург',
  'г,гурьевск': 'гурьевск',
  'г гурьевск': 'гурьевск',
  'ул калининград': 'калининград',
  'б исаково': 'большое исаково',
  'пгт чкаловск': 'чкаловск',
  'макевка': 'макеевка',
  'ленинградска обл': 'ленинградская область',
  'лениенградская обл': 'ленинградская область',
  'г. сланца': 'сланцы',
  'в.новгород': 'великий новгород',
  'г. макее': 'макеевка',
  'г.мариуп': 'мариуполь',
  'г. мелиополь': 'мелитополь',
  'г мелиополь': 'мелитополь',
  'г. лугаснк': 'луганск',
  'мелитопольул': 'мелитополь',
  'комсомолькое': 'комсомольское',
  'санкт-петеребург': 'санкт-петербург',
  'г сакнт-петербург': 'санкт-петербург',
  'гсанкт-петербург': 'санкт-петербург',
};

/**
 * A comprehensive mapping of cities and towns to their respective regions.
 * This is the primary source for determining a region based on a found city.
 */
export const REGION_BY_CITY_MAP: Record<string, string> = {
  // === РЕСПУБЛИКА АБХАЗИЯ ===
  'сухум': 'Республика Абхазия',
  'гагра': 'Республика Абхазия',
  'гудаута': 'Республика Абхазия',
  'пицунда': 'Республика Абхазия',
  'очамчира': 'Республика Абхазия',
  'новый афон': 'Республика Абхазия',
  'н афон': 'Республика Абхазия',
  'гал': 'Республика Абхазия',
  'бзыпта': 'Республика Абхазия',
  'цандрипш': 'Республика Абхазия',
  'агудзера': 'Республика Абхазия',
  'драна': 'Республика Абхазия',
  'мачара': 'Республика Абхазия',
  'амзара': 'Республика Абхазия',
  'алахадзе': 'Республика Абхазия',
  'ачарада': 'Республика Абхазия',

  // === СТАВРОПОЛЬСКИЙ КРАЙ ===
  'ставрополь': 'Ставропольский край',
  'пятигорск': 'Ставропольский край',
  'кисловодск': 'Ставропольский край',
  'невинномысск': 'Ставропольский край',
  'ессентуки': 'Ставропольский край',
  'минеральные воды': 'Ставропольский край',
  'михайловск': 'Ставропольский край',
  'георгиевск': 'Ставропольский край',
  'буденновск': 'Ставропольский край',
  'будённовск': 'Ставропольский край',
  'изобильный': 'Ставропольский край',
  'светлоград': 'Ставропольский край',
  'зеленокумск': 'Ставропольский край',
  'благодарный': 'Ставропольский край',
  'иноземцево': 'Ставропольский край',
  'новоалександровск': 'Ставропольский край',
  'нефтекумск': 'Ставропольский край',
  'лермонтов': 'Ставропольский край',
  'железноводск': 'Ставропольский край',
  'александровское': 'Ставропольский край',
  'кочубеевское': 'Ставропольский край',
  'новоселицкое': 'Ставропольский край',
  'архангельское': 'Ставропольский край',
  'прасковея': 'Ставропольский край',
  'солдато-александровское': 'Ставропольский край',
  'московское': 'Ставропольский край',
  'ессентукская': 'Ставропольский край',
  'демино': 'Ставропольский край',
  'винсады': 'Ставропольский край',
  'новотроицкая': 'Ставропольский край',
  'барьсуковская': 'Ставропольский край',
  'верхнерусское': 'Ставропольский край',
  'рыздвяный': 'Ставропольский край',
  'преображенское': 'Ставропольский край',
  'горячеводский': 'Ставропольский край',

  // === РЕСПУБЛИКА ДАГЕСТАН ===
  'махачкала': 'Республика Дагестан',
  'хасавюрт': 'Республика Дагестан',
  'дербент': 'Республика Дагестан',
  'каспийск': 'Республика Дагестан',
  'кизилюрт': 'Республика Дагестан',
  
  // === РЕСПУБЛИКА ИНГУШЕТИЯ ===
  'назрань': 'Республика Ингушетия',
  'магас': 'Республика Ингушетия',

  // === КАБАРДИНО-БАЛКАРСКАЯ РЕСПУБЛИКА ===
  'нальчик': 'Кабардино-Balkarskaya Respublika',
  'прохладный': 'Кабардино-Balkarskaya Respublika',
  'баксан': 'Кабардино-Balkarskaya Respublika',
  'нарткала': 'Кабардино-Balkarskaya Respublika',
  'чегем': 'Кабардино-Balkarskaya Respublika',
  'майский': 'Кабардино-Balkarskaya Respublika',
  'александровская': 'Кабардино-Balkarskaya Respublika',

  // === КАРАЧАЕВО-ЧЕРКЕССКАЯ РЕСПУБЛИКА ===
  'черкесск': 'Karachayevo-Cherkesskaya Respublika',
  'зеленчукская': 'Karachayevo-Cherkesskaya Respublika',

  // === РЕСПУБЛИКА СЕВЕРНАЯ ОСЕТИЯ - АЛАНИЯ ===
  'владикавказ': 'Respublika Severnaya Osetiya-Alaniya',
  'моздок': 'Respublika Severnaya Osetiya-Alaniya',
  'ардон': 'Respublika Severnaya Osetiya-Alaniya',
  'ногир': 'Respublika Severnaya Osetiya-Alaniya',

  // === ЧЕЧЕНСКАЯ РЕСПУБЛИКА ===
  'грозный': 'Chechenskaya Respublika',
  'урус-мартан': 'Chechenskaya Respublika',
  'самашки': 'Chechenskaya Respublika',

  // === РЕСПУБЛИКА КРЫМ ===
  'алупка': 'Respublika Krym',
  'алушта': 'Respublika Krym',
  'армянск': 'Respublika Krym',
  'бахчисарай': 'Respublika Krym',
  'белогорск': 'Respublika Krym',
  'джанкой': 'Respublika Krym',
  'евпатория': 'Respublika Krym',
  'керчь': 'Respublika Krym',
  'красноперекопск': 'Respublika Krym',
  'саки': 'Respublika Krym',
  'старый крым': 'Respublika Krym',
  'судак': 'Respublika Krym',
  'феодосия': 'Respublika Krym',
  'щёлкино': 'Respublika Krym',
  'щелкино': 'Respublika Krym',
  'ялта': 'Respublika Krym',
  'гвардейское': 'Respublika Krym',
  'гурзуф': 'Respublika Krym',
  'заозёрное': 'Respublika Krym',
  'коктебель': 'Respublika Krym',
  'кореиз': 'Respublika Krym',
  'красногвардейское': 'Respublika Krym',
  'ленино': 'Respublika Krym',
  'нижнегорский': 'Respublika Krym',
  'новофёдоровка': 'Respublika Krym',
  'октябрьское': 'Respublika Krym',
  'партенит': 'Respublika Krym',
  'почтовое': 'Respublika Krym',
  'раздольное': 'Respublika Krym',
  'симеиз': 'Respublika Krym',
  'уютное': 'Respublika Krym',
  'черноморское': 'Respublika Krym',
  'зуя': 'Respublika Krym',
  'вилино': 'Respublika Krym',
  'скалистое': 'Respublika Krym',
  'доброе': 'Respublika Krym',
  'инкерман': 'Sevastopol',
  'кацивели': 'Respublika Krym',
  'никита': 'Respublika Krym',
  'гаспра': 'Respublika Krym',
  'кольчугино': 'Respublika Krym',
  'угловое': 'Respublika Krym',
  'багерово': 'Respublika Krym',
  'каменка': 'Respublika Krym',
  'крымская роза': 'Respublika Krym',
  'восход': 'Respublika Krym',
  'орджоникидзе': 'Respublika Krym',

  // === КРАСНОДАРСКИЙ КРАЙ ===
  'абинск': 'Krasnodarskiy kray',
  'анапа': 'Krasnodarskiy kray',
  'апшеронск': 'Krasnodarskiy kray',
  'армавир': 'Krasnodarskiy kray',
  'белореченск': 'Krasnodarskiy kray',
  'геленджик': 'Krasnodarskiy kray',
  'горячий ключ': 'Krasnodarskiy kray',
  'гулькевичи': 'Krasnodarskiy kray',
  'ейск': 'Krasnodarskiy kray',
  'кореновск': 'Krasnodarskiy kray',
  'краснодар': 'Krasnodarskiy kray',
  'кропоткин': 'Krasnodarskiy kray',
  'крымск': 'Krasnodarskiy kray',
  'курганинск': 'Krasnodarskiy kray',
  'лабинск': 'Krasnodarskiy kray',
  'новокубанск': 'Krasnodarskiy kray',
  'новороссийск': 'Krasnodarskiy kray',
  'приморско-ахтарск': 'Krasnodarskiy kray',
  'славянск-на-кубани': 'Krasnodarskiy kray',
  'славянск на кубани': 'Krasnodarskiy kray',
  'сочи': 'Krasnodarskiy kray',
  'темрюк': 'Krasnodarskiy kray',
  'тимашевск': 'Krasnodarskiy kray',
  'тихорецк': 'Krasnodarskiy kray',
  'туапсе': 'Krasnodarskiy kray',
  'усть-лабинск': 'Krasnodarskiy kray',
  'хадыженск': 'Krasnodarskiy kray',
  'анапская': 'Krasnodarskiy kray',
  'анастасиевская': 'Krasnodarskiy kray',
  'афипский': 'Krasnodarskiy kray',
  'ахтырский': 'Krasnodarskiy kray',
  'береговое': 'Krasnodarskiy kray',
  'белозерный': 'Krasnodarskiy kray',
  'варениковская': 'Krasnodarskiy kray',
  'васюринская': 'Krasnodarskiy kray',
  'виноградный': 'Krasnodarskiy kray',
  'витязево': 'Krasnodarskiy kray',
  'вышестеблиевская': 'Krasnodarskiy kray',
  'гостагаевская': 'Krasnodarskiy kray',
  'джубга': 'Krasnodarskiy kray',
  'динская': 'Krasnodarskiy kray',
  'дивноморское': 'Krasnodarskiy kray',
  'елизаветинская': 'Krasnodarskiy kray',
  'знаменский': 'Krasnodarskiy kray',
  'ильский': 'Krasnodarskiy kray',
  'казанская': 'Krasnodarskiy kray',
  'калининская': 'Krasnodarskiy kray',
  'капустин': 'Krasnodarskiy kray',
  'коноково': 'Krasnodarskiy kray',
  'крутой': 'Krasnodarskiy kray',
  'курчанская': 'Krasnodarskiy kray',
  'лоо': 'Krasnodarskiy kray',
  'марьянская': 'Krasnodarskiy kray',
  'медведовская': 'Krasnodarskiy kray',
  'михайловская': 'Krasnodarskiy kray',
  'мостовской': 'Krasnodarskiy kray',
  'моревка': 'Krasnodarskiy kray',
  'натухаевская': 'Krasnodarskiy kray',
  'нововеличковская': 'Krasnodarskiy kray',
  'новомихайловский': 'Krasnodarskiy kray',
  'новомышастовская': 'Krasnodarskiy kray',
  'новотиторовская': 'Krasnodarskiy kray',
  'новоукраинское': 'Krasnodarskiy kray',
  'октябрьский': 'Krasnodarskiy kray',
  'павловская': 'Krasnodarskiy kray',
  'павловский': 'Krasnodarskiy kray',
  'первомайский': 'Krasnodarskiy kray',
  'пластуновская': 'Krasnodarskiy kray',
  'плодородный': 'Krasnodarskiy kray',
  'полтавская': 'Krasnodarskiy kray',
  'привольная': 'Krasnodarskiy kray',
  'раевская': 'Krasnodarskiy kray',
  'родниковская': 'Krasnodarskiy kray',
  'северская': 'Krasnodarskiy kray',
  'сенной': 'Krasnodarskiy kray',
  'старовеличковская': 'Krasnodarskiy kray',
  'старокорсунская': 'Krasnodarskiy kray',
  'старотитаровская': 'Krasnodarskiy kray',
  'супсех': 'Krasnodarskiy kray',
  'тамань': 'Krasnodarskiy kray',
  'тбилисская': 'Krasnodarskiy kray',
  'трудобеликовский': 'Krasnodarskiy kray',
  'успенское': 'Krasnodarskiy kray',
  'фастовецкая': 'Krasnodarskiy kray',
  'хутор ленина': 'Krasnodarskiy kray',
  'цемдолина': 'Krasnodarskiy kray',
  'цибанобалка': 'Krasnodarskiy kray',
  'черный': 'Krasnodarskiy kray',
  'широкая щель': 'Krasnodarskiy kray',
  'южный': 'Krasnodarskiy kray',

  // === РЕСПУБЛИКА АДЫГЕЯ ===
  'яблоновский': 'Respublika Adygeya',
  'энем': 'Respublika Adygeya',

  // === ЛУГАНСКАЯ НАРОДНАЯ РЕСПУБЛИКА ===
  'луганск': 'Luganskaya Narodnaya Respublika',
  'алчевск': 'Luganskaya Narodnaya Respublika',
  'антрацит': 'Luganskaya Narodnaya Respublika',
  'брянка': 'Luganskaya Narodnaya Respublika',
  'горское': 'Luganskaya Narodnaya Respublika',
  'зоринск': 'Luganskaya Narodnaya Respublika',
  'ирмино': 'Luganskaya Narodnaya Respublika',
  'краснодон': 'Luganskaya Narodnaya Respublika',
  'красный луч': 'Luganskaya Narodnaya Respublika',
  'лисичанск': 'Luganskaya Narodnaya Respublika',
  'молодогвардейск': 'Luganskaya Narodnaya Respublika',
  'первомайск': 'Luganskaya Narodnaya Respublika',
  'перевальск': 'Luganskaya Narodnaya Respublika',
  'ровеньки': 'Luganskaya Narodnaya Respublika',
  'рубежное': 'Luganskaya Narodnaya Respublika',
  'сватово': 'Luganskaya Narodnaya Respublika',
  'свердловск': 'Luganskaya Narodnaya Respublika',
  'северодонецк': 'Luganskaya Narodnaya Respublika',
  'старобельск': 'Luganskaya Narodnaya Respublika',
  'стаханов': 'Luganskaya Narodnaya Respublika',
  'суходольск': 'Luganskaya Narodnaya Respublika',
  'счастье': 'Luganskaya Narodnaya Respublika',
  'червонопартизанск': 'Luganskaya Narodnaya Respublika',
  'лутугино': 'Luganskaya Narodnaya Respublika',
  'александровск': 'Luganskaya Narodnaya Respublika',
  'дебальцево': 'Donetskaya Narodnaya Respublika', // Geographically contested, but often associated with DNR contextually
  'троицкое': 'Luganskaya Narodnaya Respublika',
  'новоайдар': 'Luganskaya Narodnaya Respublika',
  'юбилейный': 'Luganskaya Narodnaya Respublika',
  'мироновский': 'Donetskaya Narodnaya Respublika',
  'новый свет': 'Donetskaya Narodnaya Respublika',
  'беловодск': 'Luganskaya Narodnaya Respublika',
  'крепенский': 'Luganskaya Narodnaya Respublika',
  'щетово': 'Luganskaya Narodnaya Respublika',
  'петровское': 'Luganskaya Narodnaya Respublika',
  'атамановка': 'Luganskaya Narodnaya Respublika',
  'роскошное': 'Luganskaya Narodnaya Respublika',
  'валуйское': 'Luganskaya Narodnaya Respublika',
  'якира': 'Luganskaya Narodnaya Respublika',


  // === ДОНЕЦКАЯ НАРОДНАЯ РЕСПУБЛИКА ===
  'донецк': 'Donetskaya Narodnaya Respublika',
  'макеевка': 'Donetskaya Narodnaya Respublika',
  'мариуполь': 'Donetskaya Narodnaya Respublika',
  'горловка': 'Donetskaya Narodnaya Respublika',
  'енакиево': 'Donetskaya Narodnaya Respublika',
  'харцызск': 'Donetskaya Narodnaya Respublika',
  'шахтерск': 'Donetskaya Narodnaya Respublika',
  'торез': 'Donetskaya Narodnaya Respublika',
  'снежное': 'Donetskaya Narodnaya Respublika',
  'ясиноватая': 'Donetskaya Narodnaya Respublika',
  'кировское': 'Donetskaya Narodnaya Respublika',
  'ждановка': 'Donetskaya Narodnaya Respublika',
  'володарское': 'Donetskaya Narodnaya Respublika',
  'новотроицкое': 'Donetskaya Narodnaya Respublika',
  'иловайск': 'Donetskaya Narodnaya Respublika',
  'зугрэс': 'Donetskaya Narodnaya Respublika',
  'зугрес': 'Donetskaya Narodnaya Respublika', // spelling variation
  'волноваха': 'Donetskaya Narodnaya Respublika',
  'докучаевск': 'Donetskaya Narodnaya Respublika',
  'тельманово': 'Donetskaya Narodnaya Respublika',
  'новобешево': 'Donetskaya Narodnaya Respublika',
  'амвросиевка': 'Donetskaya Narodnaya Respublika',
  'углегорск': 'Donetskaya Narodnaya Respublika',
  'комсомольск': 'Donetskaya Narodnaya Respublika',
  'комсомольское': 'Donetskaya Narodnaya Respublika',
  'мангуш': 'Donetskaya Narodnaya Respublika',
  'заря': 'Donetskaya Narodnaya Respublika',
  'донское': 'Donetskaya Narodnaya Respublika',
  'юнокоммунаровск': 'Donetskaya Narodnaya Respublika',
  'мирный': 'Donetskaya Narodnaya Respublika',

  // === ЗАПОРОЖСКАЯ ОБЛАСТЬ ===
  'мелитополь': 'Zaporozhskaya oblast',
  'бердянск': 'Zaporozhskaya oblast',
  'энергодар': 'Zaporozhskaya oblast',
  'токмак': 'Zaporozhskaya oblast',
  'днепрорудное': 'Zaporozhskaya oblast',
  'васильевка': 'Zaporozhskaya oblast',
  'приморск': 'Zaporozhskaya oblast',
  'акимовка': 'Zaporozhskaya oblast',
  'мирное': 'Zaporozhskaya oblast',
  'михайловка': 'Zaporozhskaya oblast',
  'веселое': 'Zaporozhskaya oblast',
  'константиновка': 'Zaporozhskaya oblast',
  'молочанск': 'Zaporozhskaya oblast',
  'приазовье': 'Zaporozhskaya oblast',
  'пологи': 'Zaporozhskaya oblast',

  // === ХЕРСОНСКАЯ ОБЛАСТЬ ===
  'геническ': 'Khersonskaya oblast',
  'каховка': 'Khersonskaya oblast',
  
  // === ПРОБЛЕМНЫЕ АДРЕСА ИЗ ЗАПРОСА ===
  'орёл': 'Orlovskaya oblast',
  'орел': 'Orlovskaya oblast',
  'мценск': 'Orlovskaya oblast',
  'ливны': 'Orlovskaya oblast',
  'болхов': 'Orlovskaya oblast',
  'знаменка': 'Orlovskaya oblast',
  'нарышкино': 'Orlovskaya oblast',
  'зареченский': 'Orlovskaya oblast',
  'жилина': 'Orlovskaya oblast',
  'волково': 'Orlovskaya oblast',
  'брянск': 'Bryanskaya oblast',
  'сельцо': 'Bryanskaya oblast',
  'смоленск': 'Smolenskaya oblast',
  'сафоново': 'Smolenskaya oblast',
  'людиново': 'Kaluzhskaya oblast',
  'киров': 'Kaluzhskaya oblast',

  // === ОСНОВНЫЕ ГОРОДА РФ ===
  "москва": "Moskva",
  "санкт-петербург": "Sankt-Peterburg",
  "севастополь": "Sevastopol",
  "абакан": "Respublika Khakasiya",
  "анадырь": "Chukotskiy avtonomnyy okrug",
  "архангельск": "Arkhangelskaya oblast",
  "астрахань": "Astrakhanskaya oblast",
  "барнаул": "Altayskiy kray",
  "белгород": "Belgorodskaya oblast",
  "биробиджан": "Yevreyskaya avtonomnaya oblast",
  "благовещенск": "Amurskaya oblast",
  "владивосток": "Primorskiy kray",
  "владимир": "Vladimirskaya oblast",
  "волгоград": "Volgogradskaya oblast",
  "вологда": "Vologodskaya oblast",
  "воронеж": "Voronezhskaya oblast",
  "горно-алтайск": "Respublika Altay",
  "екатеринбург": "Sverdlovskaya oblast",
  "иваново": "Ivanovskaya oblast",
  "ижевск": "Udmurtskaya Respublika",
  "иркутск": "Irkutskaya oblast",
  "йошкар-ола": "Respublika Mariy El",
  "казань": "Respublika Tatarstan",
  "калуга": "Kaluzhskaya oblast",
  "кемерово": "Kemerovskaya oblast",
  "киров (калужская область)": "Kaluzhskaya oblast",
  // "киров": "Kirovskaya oblast", // This is ambiguous, handled by keyword map logic first
  "кострома": "Kostromskaya oblast",
  "курган": "Kurganskaya oblast",
  "курск": "Kurskaya oblast",
  "кызыл": "Respublika Tyva",
  "липецк": "Lipetskaya oblast",
  "магадан": "Magadanskaya oblast",
  "майкоп": "Respublika Adygeya",
  "мурманск": "Murmanskaya oblast",
  "нарьян-мар": "Nenetskiy avtonomnyy okrug",
  "нижний новгород": "Nizhegorodskaya oblast",
  "новосибирск": "Novosibirskaya oblast",
  "омск": "Omskaya oblast",
  "оренбург": "Orenburgskaya oblast",
  "пенза": "Penzenskaya oblast",
  "пермь": "Permskiy kray",
  "петрозаводск": "Respublika Kareliya",
  "петропавловск-камчатский": "Kamchatskiy kray",
  "псков": "Pskovskaya oblast",
  "ростов-на-дону": "Rostovskaya oblast",
  "рязань": "Ryazanskaya oblast",
  "салехард": "Yamalo-Nenetskiy avtonomnyy okrug",
  "самара": "Samarskaya oblast",
  "саранск": "Respublika Mordoviya",
  "саратов": "Saratovskaya oblast",
  "симферополь": "Respublika Krym",
  "сыктывкар": "Respublika Komi",
  "тамбов": "Tambovskaya oblast",
  "тверь": "Tverskaya oblast",
  "томск": "Tomskaya oblast",
  "тула": "Tulskaya oblast",
  "тюмень": "Tyumenskaya oblast",
  "улан-удэ": "Respublika Buryatiya",
  "ульяновск": "Ulyanovskaya oblast",
  "уфа": "Respublika Bashkortostan",
  "хабаровск": "Khabarovskiy kray",
  "ханты-мансийск": "Khanty-Mansiyskiy avtonomnyy okrug - Yugra",
  "чебоксары": "Chuvashskaya Respublika",
  "челябинск": "Chelyabinskaya oblast",
  "чита": "Zabaykalskiy kray",
  "элиста": "Respublika Kalmykiya",
  "южно-сахалинск": "Sakhalinskaya oblast",
  "якутск": "Respublika Sakha (Yakutiya)",
  "ярославль": "Yaroslavskaya oblast",
  
  // === КАЛИНИНГРАДСКАЯ ОБЛАСТЬ ===
  'калининград': 'Kaliningradskaya oblast',
  'советск': 'Kaliningradskaya oblast',
  'черняховск': 'Kaliningradskaya oblast',
  'балтийск': 'Kaliningradskaya oblast',
  'гусев': 'Kaliningradskaya oblast',
  'светлый': 'Kaliningradskaya oblast',
  'гурьевск': 'Kaliningradskaya oblast',
  'зеленоградск': 'Kaliningradskaya oblast',
  'гвардейск': 'Kaliningradskaya oblast',
  'светлогорск': 'Kaliningradskaya oblast',
  'пионерский': 'Kaliningradskaya oblast',
  'неман': 'Kaliningradskaya oblast',
  'мамоново': 'Kaliningradskaya oblast',
  'полесск': 'Kaliningradskaya oblast',
  'багратионовск': 'Kaliningradskaya oblast',
  'правдинск': 'Kaliningradskaya oblast',
  'нестеров': 'Kaliningradskaya oblast',
  'озерск': 'Kaliningradskaya oblast',
  'большое исаково': 'Kaliningradskaya oblast',
  'васильково': 'Kaliningradskaya oblast',
  'голубево': 'Kaliningradskaya oblast',
  'чкаловск': 'Kaliningradskaya oblast',
  'матросово': 'Kaliningradskaya oblast',

  // === САНКТ-ПЕТЕРБУРГ (ФЕДЕРАЛЬНЫЙ ГОРОД) ===
  'колпино': 'Sankt-Peterburg',
  'пушкин': 'Sankt-Peterburg',
  'петергоф': 'Sankt-Peterburg',
  'сестрорецк': 'Sankt-Peterburg',
  'кронштадт': 'Sankt-Peterburg',
  'ломоносов': 'Sankt-Peterburg',
  'павловск': 'Sankt-Peterburg',
  'зеленогорск': 'Sankt-Peterburg',
  'шушары': 'Sankt-Peterburg',
  'парголово': 'Sankt-Peterburg',
  'понтонный': 'Sankt-Peterburg',
  'горелово': 'Sankt-Peterburg',
  'ново-ковалево': 'Sankt-Peterburg',

  // === ЛЕНИНГРАДСКАЯ ОБЛАСТЬ ===
  'всеволожск': 'Leningradskaya oblast',
  'выборг': 'Leningradskaya oblast',
  'гатчина': 'Leningradskaya oblast',
  'сосновый бор': 'Leningradskaya oblast',
  'кировск': 'Leningradskaya oblast',
  'тосно': 'Leningradskaya oblast',
  'кудрово': 'Leningradskaya oblast',
  'мурино': 'Leningradskaya oblast',
  'коммунар': 'Leningradskaya oblast',
  'тихвин': 'Leningradskaya oblast',
  'сланцы': 'Leningradskaya oblast',
  'приозерск': 'Leningradskaya oblast',
  'волхов': 'Leningradskaya oblast',
  'кириши': 'Leningradskaya oblast',
  'луга': 'Leningradskaya oblast',
  'дятлицы': 'Leningradskaya oblast',
  'сиверский': 'Leningradskaya oblast',
  'свердлова': 'Leningradskaya oblast',
  'токсово': 'Leningradskaya oblast',
  'вырица': 'Leningradskaya oblast',
  'волосово': 'Leningradskaya oblast',
  'большая ижора': 'Leningradskaya oblast',
  'ивангород': 'Leningradskaya oblast',
  'тайцы': 'Leningradskaya oblast',
  'разметелево': 'Leningradskaya oblast',
  'колтуши': 'Leningradskaya oblast',
  'подпорожье': 'Leningradskaya oblast',
  'тельмана': 'Leningradskaya oblast',
  'сертолово': 'Leningradskaya oblast',
  'новогорелово': 'Leningradskaya oblast',
  'лодейное поле': 'Leningradskaya oblast',
  'кингисепп': 'Leningradskaya oblast',
  'аннолово': 'Leningradskaya oblast',
  'корнево': 'Leningradskaya oblast',
  'иннолово': 'Leningradskaya oblast',
  'борисова грива': 'Leningradskaya oblast',
  'агалатово': 'Leningradskaya oblast',
  'федоровское': 'Leningradskaya oblast',
  'бугры': 'Leningradskaya oblast',
  'романовка': 'Leningradskaya oblast',
  'рахья': 'Leningradskaya oblast',
  'васкелово': 'Leningradskaya oblast',
  'руссковицы': 'Leningradskaya oblast',
  'пупышево': 'Leningradskaya oblast',
  'дунай': 'Leningradskaya oblast',
  'апраксин': 'Leningradskaya oblast',
  'грибное': 'Leningradskaya oblast',
  'красницы': 'Leningradskaya oblast',
  'вяхтелево': 'Leningradskaya oblast',
  'вартемяги': 'Leningradskaya oblast',
  'медное озеро': 'Leningradskaya oblast',
  'пигелево': 'Leningradskaya oblast',
  'виллози': 'Leningradskaya oblast',
  'черная речка': 'Leningradskaya oblast',
  'рощинское': 'Leningradskaya oblast',
  'малые колпаны': 'Leningradskaya oblast',
  'энколово': 'Leningradskaya oblast',
  'порошкино': 'Leningradskaya oblast',
  'пудость': 'Leningradskaya oblast',

  // === НОВГОРОДСКАЯ ОБЛАСТЬ ===
  'великий новгород': 'Novgorodskaya oblast',
  'трубичино': 'Novgorodskaya oblast',
  'новая деревня': 'Novgorodskaya oblast',
  'валдай': 'Novgorodskaya oblast',
  'короцко': 'Novgorodskaya oblast',

  // === СТРАНЫ СНГ (Пример) ===
  "минск": "Respublika Belarus",
  "гомель": "Respublika Belarus",
  "астана": "Respublika Kazakhstan",
  "алматы": "Respublika Kazakhstan",
};


export const REGION_KEYWORD_MAP: Record<string, string> = {
  'абхазия': 'Respublika Abkhaziya',
  // Новые регионы
  'луганская народная респ': 'Luganskaya Narodnaya Respublika',
  'луганская респ': 'Luganskaya Narodnaya Respublika',
  'лнр': 'Luganskaya Narodnaya Respublika',
  'донецкая народная респ': 'Donetskaya Narodnaya Respublika',
  'донецкая респ': 'Donetskaya Narodnaya Respublika',
  'днр': 'Donetskaya Narodnaya Respublika',
  'рсо-алания': 'Respublika Severnaya Osetiya-Alaniya',
  'чр': 'Chechenskaya Respublika',
  
  // Районы ( Districts ) - very reliable identifier
  'гурьевский р-н': 'Kaliningradskaya oblast',
  'ломоносовский р-н': 'Leningradskaya oblast',
  'гатчинский р-н': 'Leningradskaya oblast',
  'гатчинский район': 'Leningradskaya oblast',
  'всеволожский р-н': 'Leningradskaya oblast',
  'всеволожский район': 'Leningradskaya oblast',
  'тосненский р-н': 'Leningradskaya oblast',
  'тосненский район': 'Leningradskaya oblast',
  'выборгский р-н': 'Leningradskaya oblast',
  'красносельский район': 'Sankt-Peterburg',
  'колпинский': 'Sankt-Peterburg',
  'волосовский район': 'Leningradskaya oblast',
  'пушкинский район': 'Sankt-Peterburg',
  'кировский район': 'Leningradskaya oblast',
  'новгородский р-н': 'Novgorodskaya oblast',
  'валдайский р-н': 'Novgorodskaya oblast',
  'волновахский р-н': 'Donetskaya Narodnaya Respublika',
  'станично-луганский': 'Luganskaya Narodnaya Respublika',
  'краснодарский кр': 'Krasnodarskiy kray',
  'кк': 'Krasnodarskiy kray',
  'динской р-н': 'Krasnodarskiy kray',
  'адлерский район': 'Krasnodarskiy kray',
  'гулькевичевский р-н': 'Krasnodarskiy kray',
  'анапский р-н': 'Krasnodarskiy kray',
  'темрюкский р-н': 'Krasnodarskiy kray',
  'северский р-н': 'Krasnodarskiy kray',
  'курганинский район': 'Krasnodarskiy kray',
  'тихорецкий район': 'Krasnodarskiy kray',
  'красноармейский р-н': 'Krasnodarskiy kray',
  'апшеронский р-н': 'Krasnodarskiy kray',
  'тимашевский р-н': 'Krasnodarskiy kray',
  'павловский р-н': 'Krasnodarskiy kray',
  'каневской район': 'Krasnodarskiy kray',
  'туапсинский р-н': 'Krasnodarskiy kray',
  'ейский р-н': 'Krasnodarskiy kray',
  'симферопольский р-н': 'Respublika Krym',
  'белогорский р-н': 'Respublika Krym',
  'сакский р-н': 'Respublika Krym',
  'красногвардейский р-н': 'Respublika Krym',
  'минераловодский район': 'Stavropolskiy kray',
  'буденновский р-н': 'Stavropolskiy kray',
  'аннинское городское поселение': 'Leningradskaya oblast',
  'пудомягское сельское поселение': 'Leningradskaya oblast',
  'рощинское': 'Leningradskaya oblast',


  // Короткие и неоднозначные сокращения, которые теперь ищутся как отдельные слова
  'ло': 'Leningradskaya oblast',
  'лен обл': 'Leningradskaya oblast',
  'спб': 'Sankt-Peterburg',
  'петербург': 'Sankt-Peterburg',
  'кал-я обл': 'Kaliningradskaya oblast',
  
  // Полные и частичные названия регионов
  'адыгея': 'Respublika Adygeya',
  'алтай респ': 'Respublika Altay',
  'башкортостан': 'Respublika Bashkortostan', 'башкирия': 'Respublika Bashkortostan',
  'бурятия': 'Respublika Buryatiya',
  'дагестан': 'Respublika Dagestan',
  'ингушетия': 'Respublika Ingushetiya',
  'кбр': 'Kabardino-Balkarskaya Respublika', 'кабардино-балкарская': 'Kabardino-Balkarskaya Respublika',
  'калмыкия': 'Respublika Kalmykiya',
  'кчр': 'Karachayevo-Cherkesskaya Respublika', 'карачаево-черкесская': 'Karachayevo-Cherkesskaya Respublika',
  'карелия': 'Respublika Kareliya',
  'коми': 'Respublika Komi',
  'крым': 'Respublika Krym',
  'марий эл': 'Respublika Mariy El',
  'мордовия': 'Respublika Mordoviya',
  'саха': 'Respublika Sakha (Yakutiya)', 'якутия': 'Respublika Sakha (Yakutiya)',
  'северная осетия': 'Respublika Severnaya Osetiya-Alaniya', 'алания': 'Respublika Severnaya Osetiya-Alaniya',
  'татарстан': 'Respublika Tatarstan',
  'тыва': 'Respublika Tyva', 'тува': 'Respublika Tyva',
  'удмуртия': 'Udmurtskaya Respublika',
  'хакасия': 'Respublika Khakasiya',
  'чечня': 'Chechenskaya Respublika', 'чеченская': 'Chechenskaya Respublika',
  'чувашия': 'Chuvashskaya Respublika', 'чувашская': 'Chuvashskaya Respublika',
  'алтайский край': 'Altayskiy kray',
  'забайкальский край': 'Zabaykalskiy kray',
  'камчатский край': 'Kamchatskiy kray',
  'краснодарский край': 'Krasnodarskiy kray', 'кубань': 'Krasnodarskiy kray',
  'красноярский край': 'Krasnoyarskiy kray',
  'пермский край': 'Permskiy kray',
  'приморский край': 'Primorskiy kray',
  'ставропольский край': 'Stavropolskiy kray',
  'хабаровский край': 'Khabarovskiy kray',
  'амурская обл': 'Amurskaya oblast', 'амурская область': 'Amurskaya oblast', 'обл амурская': 'Amurskaya oblast', 'амурская': 'Amurskaya oblast',
  'архангельская обл': 'Arkhangelskaya oblast', 'архангельская область': 'Arkhangelskaya oblast', 'обл архангельская': 'Arkhangelskaya oblast', 'архангельская': 'Arkhangelskaya oblast',
  'астраханская обл': 'Astrakhanskaya oblast', 'астраханская область': 'Astrakhanskaya oblast', 'обл астраханская': 'Astrakhanskaya oblast', 'астраханская': 'Astrakhanskaya oblast',
  'белгородская обл': 'Belgorodskaya oblast', 'белгородская область': 'Belgorodskaya oblast', 'обл белгородская': 'Belgorodskaya oblast', 'белгородская': 'Belgorodskaya oblast',
  'брянская обл': 'Bryanskaya oblast', 'брянская область': 'Bryanskaya oblast', 'обл брянская': 'Bryanskaya oblast', 'брянская': 'Bryanskaya oblast', 'г брянск': 'Bryanskaya oblast',
  'владимирская обл': 'Vladimirskaya oblast', 'владимирская область': 'Vladimirskaya oblast', 'обл владимирская': 'Vladimirskaya oblast', 'владимирская': 'Vladimirskaya oblast',
  'волгоградская обл': 'Volgogradskaya oblast', 'волгоградская область': 'Volgogradskaya oblast', 'обл волгоградская': 'Volgogradskaya oblast', 'волгоградская': 'Volgogradskaya oblast',
  'вологодская обл': 'Vologodskaya oblast', 'вологодская область': 'Volgogradskaya oblast', 'обл вологодская': 'Vologodskaya oblast', 'вологодская': 'Vologodskaya oblast',
  'воронежская обл': 'Voronezhskaya oblast', 'воронежская область': 'Voronezhskaya oblast', 'обл воронежская': 'Voronezhskaya oblast', 'воронежская': 'Voronezhskaya oblast',
  'ивановская обл': 'Ivanovskaya oblast', 'ивановская область': 'Ivanovskaya oblast', 'обл ивановская': 'Ivanovskaya oblast', 'ивановская': 'Ivanovskaya oblast',
  'иркутская обл': 'Irkutskaya oblast', 'иркутская область': 'Irkutskaya oblast', 'обл иркутская': 'Irkutskaya oblast', 'иркутская': 'Irkutskaya oblast',
  'калининградская обл': 'Kaliningradskaya oblast', 'калининградская область': 'Kaliningradskaya oblast', 'обл калининградская': 'Kaliningradskaya oblast', 'калининградская': 'Kaliningradskaya oblast',
  'калужская обл': 'Kaluzhskaya oblast', 'калужская область': 'Kaluzhskaya oblast', 'обл калужская': 'Kaluzhskaya oblast', 'калужская': 'Kaluzhskaya oblast', 'г киров': 'Kaluzhskaya oblast',
  'кемеровская обл': 'Kemerovskaya oblast', 'кемеровская область': 'Kemerovskaya oblast', 'обл кемеровская': 'Kemerovskaya oblast', 'кемеровская': 'Kemerovskaya oblast', 'кузбасс': 'Kemerovskaya oblast',
  'кировская обл': 'Kirovskaya oblast', 'кировская область': 'Kirovskaya oblast', 'обл кировская': 'Kirovskaya oblast', 'кировская': 'Kirovskaya oblast',
  'костромская обл': 'Kostromskaya oblast', 'костромская область': 'Kostromskaya oblast', 'обл костромская': 'Kostromskaya oblast', 'костромская': 'Kostromskaya oblast',
  'курганская обл': 'Kurganskaya oblast', 'курганская область': 'Kurganskaya oblast', 'обл курганская': 'Kurganskaya oblast', 'курганская': 'Kurganskaya oblast',
  'курская обл': 'Kurskaya oblast', 'курская область': 'Kurskaya oblast', 'обл курская': 'Kurskaya oblast', 'курская': 'Kurskaya oblast',
  'ленинградская обл': 'Leningradskaya oblast', 'ленинградская область': 'Leningradskaya oblast', 'обл ленинградская': 'Leningradskaya oblast', 'ленинградская': 'Leningradskaya oblast',
  'липецкая обл': 'Lipetskaya oblast', 'липецкая область': 'Lipetskaya oblast', 'обл липецкая': 'Lipetskaya oblast', 'липецкая': 'Lipetskaya oblast',
  'магаданская обл': 'Magadanskaya oblast', 'магаданская область': 'Magadanskaya oblast', 'обл магаданская': 'Magadanskaya oblast', 'магаданская': 'Magadanskaya oblast',
  'московская обл': 'Moskovskaya oblast', 'московская область': 'Moskovskaya oblast', 'обл московская': 'Moskovskaya oblast', 'московская': 'Moskovskaya oblast', 'мособласть': 'Moskovskaya oblast', 'подмосковье': 'Moskovskaya oblast',
  'мурманская обл': 'Murmanskaya oblast', 'мурманская область': 'Murmanskaya oblast', 'обл мурманская': 'Murmanskaya oblast', 'мурманская': 'Murmanskaya oblast',
  'нижегородская обл': 'Nizhegorodskaya oblast', 'нижегородская область': 'Nizhegorodskaya oblast', 'обл нижегородская': 'Nizhegorodskaya oblast', 'нижегородская': 'Nizhegorodskaya oblast',
  'новгородская обл': 'Novgorodskaya oblast', 'новгородская область': 'Novgorodskaya oblast', 'обл новгородская': 'Novgorodskaya oblast', 'новгородская': 'Novgorodskaya oblast',
  'новосибирская обл': 'Novosibirskaya oblast', 'новосибирская область': 'Novosibirskaya oblast', 'обл новосибирская': 'Novosibirskaya oblast', 'новосибирская': 'Novosibirskaya oblast',
  'омская обл': 'Omskaya oblast', 'омская область': 'Omskaya oblast', 'обл омская': 'Omskaya oblast', 'омская': 'Omskaya oblast',
  'оренбургская обл': 'Orenburgskaya oblast', 'оренбургская область': 'Orenburgskaya oblast', 'обл оренбургская': 'Orenburgskaya oblast', 'оренбургская': 'Orenburgskaya oblast',
  'орловская обл': 'Orlovskaya oblast', 'орловская область': 'Orlovskaya oblast', 'обл орловская': 'Orlovskaya oblast', 'орловская': 'Orlovskaya oblast', 'г орёл': 'Orlovskaya oblast', 'г орел': 'Orlovskaya oblast',
  'пензенская обл': 'Penzenskaya oblast', 'пензенская область': 'Penzenskaya oblast', 'обл пензенская': 'Penzenskaya oblast', 'пензенская': 'Penzenskaya oblast',
  'псковская обл': 'Pskovskaya oblast', 'псковская область': 'Pskovskaya oblast', 'обл псковская': 'Pskovskaya oblast', 'псковская': 'Pskovskaya oblast',
  'ростовская обл': 'Rostovskaya oblast', 'ростовская область': 'Rostovskaya oblast', 'обл ростовская': 'Rostovskaya oblast', 'ростовская': 'Rostovskaya oblast',
  'рязанская обл': 'Ryazanskaya oblast', 'рязанская область': 'Ryazanskaya oblast', 'обл рязанская': 'Ryazanskaya oblast', 'рязанская': 'Ryazanskaya oblast',
  'самарская обл': 'Samarskaya oblast', 'самарская область': 'Samarskaya oblast', 'обл самарская': 'Samarskaya oblast', 'самарская': 'Samarskaya oblast',
  'саратовская обл': 'Saratovskaya oblast', 'саратовская область': 'Saratovskaya oblast', 'обл саратовская': 'Saratovskaya oblast', 'саратовская': 'Saratovskaya oblast',
  'сахалинская обл': 'Sakhalinskaya oblast', 'сахалинская область': 'Sakhalinskaya oblast', 'обл сахалинская': 'Sakhalinskaya oblast', 'сахалинская': 'Sakhalinskaya oblast',
  'свердловская обл': 'Sverdlovskaya oblast', 'свердловская область': 'Sverdlovskaya oblast', 'обл свердловская': 'Sverdlovskaya oblast', 'свердловская': 'Sverdlovskaya oblast',
  'смоленская обл': 'Smolenskaya oblast', 'смоленская область': 'Smolenskaya oblast', 'обл смоленская': 'Smolenskaya oblast', 'смоленская': 'Smolenskaya oblast', 'г смоленск': 'Smolenskaya oblast',
  'тамбовская обл': 'Tambovskaya oblast', 'тамбовская область': 'Tambovskaya oblast', 'обл тамбовская': 'Tambovskaya oblast', 'тамбовская': 'Tambovskaya oblast',
  'тверская обл': 'Tverskaya oblast', 'тверская область': 'Tverskaya oblast', 'обл тверская': 'Tverskaya oblast', 'тверская': 'Tverskaya oblast',
  'томская обл': 'Tomskaya oblast', 'томская область': 'Tomskaya oblast', 'обл томская': 'Tomskaya oblast', 'томская': 'Tomskaya oblast',
  'тульская обл': 'Tulskaya oblast', 'тульская область': 'Tulskaya oblast', 'обл тульская': 'Tulskaya oblast', 'тульская': 'Tulskaya oblast',
  'тюменская обл': 'Tyumenskaya oblast', 'тюменская область': 'Tyumenskaya oblast', 'обл тюменская': 'Tyumenskaya oblast', 'тюменская': 'Tyumenskaya oblast',
  'ульяновская обл': 'Ulyanovskaya oblast', 'ульяновская область': 'Ulyanovskaya oblast', 'обл ульяновская': 'Ulyanovskaya oblast', 'ульяновская': 'Ulyanovskaya oblast',
  'челябинская обл': 'Chelyabinskaya oblast', 'челябинская область': 'Chelyabinskaya oblast', 'обл челябинская': 'Chelyabinskaya oblast', 'челябинская': 'Chelyabinskaya oblast',
  'ярославская обл': 'Yaroslavskaya oblast', 'ярославская область': 'Yaroslavskaya oblast', 'обл ярославская': 'Yaroslavskaya oblast', 'ярославская': 'Yaroslavskaya oblast',
  'запорожская обл': 'Zaporozhskaya oblast', 'запорожская': 'Zaporozhskaya oblast', 'обл запорожская': 'Zaporozhskaya oblast',
  'херсонская обл': 'Khersonskaya oblast', 'херсонская': 'Khersonskaya oblast', 'обл херсонская': 'Khersonskaya oblast',
  'ненецкий ао': 'Nenetskiy avtonomnyy okrug',
  'хмао': 'Khanty-Mansiyskiy avtonomnyy okrug - Yugra', 'югра': 'Khanty-Mansiyskiy avtonomnyy okrug - Yugra',
  'чукотский ао': 'Chukotskiy avtonomnyy okrug', 'чукотка': 'Chukotskiy avtonomnyy okrug',
  'янао': 'Yamalo-Nenetskiy avtonomnyy okrug', 'ямал': 'Yamalo-Nenetskiy avtonomnyy okrug',
  'еврейская ао': 'Yevreyskaya avtonomnaya oblast',
  // СНГ
  'беларусь': 'Respublika Belarus', 'белоруссия': 'Respublika Belarus',
  'казахстан': 'Respublika Kazakhstan',
  'армения': 'Armeniya',
  'киргизия': 'Kyrgyzskaya Respublika', 'кыргызстан': 'Kyrgyzskaya Respublika',
};


export const INDEX_MAP: Record<string, string> = {
    // Префиксы индексов
    '241': 'Bryanskaya oblast', '242': 'Bryanskaya oblast', '243': 'Bryanskaya oblast',
    '302': 'Orlovskaya oblast', '303': 'Orlovskaya oblast',
    '214': 'Smolenskaya oblast', '215': 'Smolenskaya oblast', '216': 'Smolenskaya oblast',
    '236': 'Kaliningradskaya oblast', '238': 'Kaliningradskaya oblast',
    '295': 'Respublika Krym', '296': 'Respublika Krym', '297': 'Respublika Krym', '298': 'Respublika Krym',
    '350': 'Krasnodarskiy kray', '351': 'Krasnodarskiy kray', '352': 'Krasnodarskiy kray', '353': 'Krasnodarskiy kray', '354': 'Krasnodarskiy kray',
    '101': 'Moskva', '102': 'Moskva', '103': 'Moskva', '104': 'Moskva', '105': 'Moskva', '106': 'Moskva', '107': 'Moskva', '108': 'Moskva', '109': 'Moskva', '111': 'Moskva', '115': 'Moskva', '117': 'Moskva', '119': 'Moskva', '121': 'Moskva', '123': 'Moskva', '124': 'Moskva', '125': 'Moskva', '127': 'Moskva', '129': 'Moskva', '131': 'Moskva', '133': 'Moskva', '135': 'Moskva',
    '140': 'Moskovskaya oblast', '141': 'Moskovskaya oblast', '142': 'Moskovskaya oblast', '143': 'Moskovskaya oblast',
    '187': 'Leningradskaya oblast', '188': 'Leningradskaya oblast',
    '190': 'Sankt-Peterburg', '191': 'Sankt-Peterburg', '192': 'Sankt-Peterburg', '193': 'Sankt-Peterburg', '194': 'Sankt-Peterburg', '195': 'Sankt-Peterburg', '196': 'Sankt-Peterburg', '197': 'Sankt-Peterburg', '198': 'Sankt-Peterburg',
    '173': 'Novgorodskaya oblast',
    '361': 'Kabardino-Balkarskaya Respublika',
    '249': 'Kaluzhskaya oblast',
    '283': 'Donetskaya Narodnaya Respublika', '286': 'Donetskaya Narodnaya Respublika', '287': 'Donetskaya Narodnaya Respublika',
    '272': 'Zaporozhskaya oblast',
    '284': 'Luganskaya Narodnaya Respublika', '291': 'Luganskaya Narodnaya Respublika',
    '385': 'Respublika Adygeya',
    '355': 'Stavropolskiy kray', '356': 'Stavropolskiy kray', '357': 'Stavropolskiy kray',
    '344': 'Rostovskaya oblast', '346': 'Rostovskaya oblast', '347': 'Rostovskaya oblast',
};

/**
 * Standardizes a region name to a consistent format.
 * Ensures the final output is clean, capitalized, and matches the official name.
 * @param input The detected region string.
 * @returns A standardized region name or the default "Регион не определен".
 */
export const standardizeRegion = (input: string | null | undefined): string => {
    if (!input) return 'Регион не определен';
    
    // The maps already contain the standardized names. This function primarily acts as a final formatter.
    const cleanInput = input.trim();
    
    // Check if the input is already a standardized value from our maps
    const allStandardValues = new Set([...Object.values(REGION_BY_CITY_MAP), ...Object.values(REGION_KEYWORD_MAP)]);
    if (allStandardValues.has(cleanInput)) {
        return cleanInput;
    }

    // Capitalize and return as a last resort
    return capitalize(cleanInput);
};